M = traj(trajout.signals.values(:,1),...
	 trajout.signals.values(:,2),...
	 trajout.signals.values(:,3),...
	 trajout.signals.values(:,4),...
	 trajout.signals.values(:,5),...
	 trajout.signals.values(:,6),...
	 25,1);

movie(M,1,inv(diff(trajout.time(1:2))));
